version: '3.9'

services:
  salones-api:
    container_name: salones-api
    image: salones-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java-db:3306/crudsalones
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=admin
    depends_on:
      - java-db
  java-db:
    container_name: java-db
    image: mysql